const routes = require('next-routes')


module.exports = routes()
  .add("index", "/")
  .add("dashboard", "/dashboard/in")
  .add("eventplanner", "/dashboard/eventplanner")
  .add("prayerrequest", "/dashboard/prayerrequest")
  .add("inboxview", "/dashboard/prayerrequest/inboxview")
  .add("resources", "/dashboard/resources")
  .add("upload-form", "/dashboard/resources/upload-form")
  .add("livestream", "/dashboard/livestream")
  .add("livestreamform", "/dashboard/livestream/livestreamform")
  .add("livestreamview", "/dashboard/livestream/livestreamview")
  .add("wallet", "/dashboard/wallet")
  .add("all-wallet-view", "/dashboard/wallet/all-wallet-view")
